"""Initial migration for both databases

Revision ID: 46a42c9e6df1
Revises: 482f03e0286d
Create Date: 2024-07-29 10:10:14.563361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '46a42c9e6df1'
down_revision = '482f03e0286d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.drop_index('opportunity_id_index')

    op.drop_table('opportunity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('opportunity_id', sa.INTEGER(), nullable=False),
    sa.Column('long_text', sa.TEXT(), nullable=False),
    sa.Column('embedding_vector', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id')
    )
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.create_index('opportunity_id_index', ['opportunity_id'], unique=False)

    # ### end Alembic commands ###
