"""Initial migration.

Revision ID: 482f03e0286d
Revises: 
Create Date: 2024-07-17 12:14:34.869206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482f03e0286d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('opportunity_id', sa.Integer(), nullable=False, unique=True),
        sa.Column('long_text', sa.Text(), nullable=False),
        sa.Column('embedding_vector', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opportunity')
    # ### end Alembic commands ###
